// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoAPI.Data.Database;

#nullable disable

namespace TodoAPI.Data.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    partial class TodoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("TodoAPI.Data.Models.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Secret")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a2a704f-2872-494d-abf7-8cbe952669d9"),
                            IsComplete = false,
                            Name = "Jerry",
                            Secret = "Guy"
                        },
                        new
                        {
                            Id = new Guid("38f45965-20cd-4581-acd5-d9543f3162d7"),
                            IsComplete = true,
                            Name = "Sam",
                            Secret = "Test"
                        },
                        new
                        {
                            Id = new Guid("933024aa-8aaa-4aa2-860b-16989a059edb"),
                            IsComplete = false,
                            Name = "Ian",
                            Secret = "Other"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
